//! Vaporizer2のpatch名先頭2文字を、selector用カテゴリ名へ展開する表。

pub const VAPORIZER2_CATEGORY_CODES: [(&str, &str); 28] = [
    ("AR", "Arpeggio"),
    ("AT", "Atmosphere"),
    ("BA", "Bass"),
    ("BL", "Bell"),
    ("BR", "Brass"),
    ("CH", "Chord"),
    ("DK", "Drum kit"),
    ("DL", "Drum loop"),
    ("DR", "Drum"),
    ("FX", "Effect"),
    ("GT", "Guitar"),
    ("IN", "Instrument"),
    ("KB", "Keyboard"),
    ("LD", "Lead"),
    ("MA", "Mallet"),
    ("OC", "Orchestral"),
    ("OR", "Organ"),
    ("PD", "Pad"),
    ("PL", "Plucked"),
    ("PN", "Piano"),
    ("RD", "Reed"),
    ("RI", "Riser"),
    ("SQ", "Sequence"),
    ("ST", "String"),
    ("SY", "Synth"),
    ("TG", "Trancegate"),
    ("VC", "Vocal"),
    ("WW", "Woodwind"),
];
