//! effect 種別ごとの parameter layout（storage 順の並びと GUI 側の並びの対応）。
//!
//! `scripts/gen_surge_fx_param_layout.py` が Surge XT のソースから生成する。
//! 手で編集せず、スクリプトを直すこと。

use super::SURGE_FX_PARAM_COUNT;

/// 1 effect 種別ぶんの layout。配列はすべて storage index（`.srgfx` の `pN`）順。
#[derive(Clone, Copy, Debug)]
pub struct SurgeFxParamLayout {
    pub fx_type: i32,
    pub display_name: &'static str,
    /// GUI の並びを決める offset。0 なら GUI の並びに参加しない。
    pub posy_offset: [i32; SURGE_FX_PARAM_COUNT],
    /// `ct_none` でない（値が流れる）parameter。
    pub active: [bool; SURGE_FX_PARAM_COUNT],
    /// plugin が `clap.params` で名乗る名前（group 名を除く）。
    pub names: [&'static str; SURGE_FX_PARAM_COUNT],
}

pub const SURGE_FX_PARAM_LAYOUTS: &[SurgeFxParamLayout] = &[
    SurgeFxParamLayout {
        fx_type: 1,
        display_name: "Delay",
        posy_offset: [5, 5, 7, 7, 7, 7, 9, 9, -15, 0, 9, 5],
        active: [
            true, true, true, true, true, true, true, true, true, false, true, true,
        ],
        names: [
            "Left",
            "Right",
            "Feedback",
            "Crossfeed",
            "Low Cut",
            "High Cut",
            "Rate",
            "Depth",
            "Channel",
            "",
            "Mix",
            "Width",
        ],
    },
    SurgeFxParamLayout {
        fx_type: 2,
        display_name: "Reverb 1",
        posy_offset: [1, 3, 3, 3, 3, 5, 5, 5, 5, 9, 5, 0],
        active: [
            true, true, true, true, true, true, true, true, true, true, true, false,
        ],
        names: [
            "Pre-Delay",
            "Room Shape",
            "Size",
            "Decay Time",
            "HF Damping",
            "Low Cut",
            "Peak Freq",
            "Peak Gain",
            "High Cut",
            "Mix",
            "Width",
            "",
        ],
    },
    SurgeFxParamLayout {
        fx_type: 3,
        display_name: "Phaser",
        posy_offset: [15, 17, 13, -3, -3, -3, 17, 13, -5, -5, -19, 1],
        active: [
            true, true, true, true, true, true, true, true, true, true, true, true,
        ],
        names: [
            "Center",
            "Feedback",
            "Sharpness",
            "Rate",
            "Depth",
            "Stereo",
            "Mix",
            "Width",
            "Count",
            "Spread",
            "Waveform",
            "Tone",
        ],
    },
    SurgeFxParamLayout {
        fx_type: 4,
        display_name: "Rotary Speaker",
        posy_offset: [1, 11, 11, -3, 1, -3, 7, 7, 0, 0, 0, 0],
        active: [
            true, true, true, true, true, true, true, true, false, false, false, false,
        ],
        names: [
            "Horn Rate",
            "Doppler",
            "Tremolo",
            "Rotor Rate",
            "Drive",
            "Model",
            "Width",
            "Mix",
            "",
            "",
            "",
            "",
        ],
    },
    SurgeFxParamLayout {
        fx_type: 5,
        display_name: "Distortion",
        posy_offset: [1, 1, 1, 1, 5, 5, 7, 7, 7, 7, 9, -11],
        active: [
            true, true, true, true, true, true, true, true, true, true, true, true,
        ],
        names: [
            "Gain",
            "Frequency",
            "Bandwidth",
            "High Cut",
            "Drive",
            "Feedback",
            "Gain",
            "Frequency",
            "Bandwidth",
            "High Cut",
            "Gain",
            "Model",
        ],
    },
    SurgeFxParamLayout {
        fx_type: 6,
        display_name: "EQ",
        posy_offset: [1, 1, 1, 3, 3, 3, 5, 5, 5, 7, 7, 0],
        active: [
            true, true, true, true, true, true, true, true, true, true, true, false,
        ],
        names: [
            "Gain 1",
            "Frequency 1",
            "Bandwidth 1",
            "Gain 2",
            "Frequency 2",
            "Bandwidth 2",
            "Gain 3",
            "Frequency 3",
            "Bandwidth 3",
            "Gain",
            "Mix",
            "",
        ],
    },
    SurgeFxParamLayout {
        fx_type: 7,
        display_name: "Frequency Shifter",
        posy_offset: [1, 1, 3, 3, 5, 0, 0, 0, 0, 0, 0, 0],
        active: [
            true, true, true, true, true, false, false, false, false, false, false, false,
        ],
        names: [
            "Left", "Right", "Time", "Feedback", "Mix", "", "", "", "", "", "", "",
        ],
    },
    SurgeFxParamLayout {
        fx_type: 8,
        display_name: "Conditioner",
        posy_offset: [1, 1, 3, 5, 13, 13, 13, 15, -7, 0, 0, 0],
        active: [
            true, true, true, true, true, true, true, true, true, false, false, false,
        ],
        names: [
            "Bass",
            "Treble",
            "Width",
            "Balance",
            "Threshold",
            "Attack Rate",
            "Release Rate",
            "Gain",
            "Side Low Cut",
            "",
            "",
            "",
        ],
    },
    SurgeFxParamLayout {
        fx_type: 9,
        display_name: "Chorus",
        posy_offset: [7, -1, -1, 3, 5, 5, 9, 5, 0, 0, 0, 0],
        active: [
            true, true, true, true, true, true, true, true, false, false, false, false,
        ],
        names: [
            "Time", "Rate", "Depth", "Feedback", "Low Cut", "High Cut", "Mix", "Width", "", "", "",
            "",
        ],
    },
    SurgeFxParamLayout {
        fx_type: 10,
        display_name: "Vocoder",
        posy_offset: [1, 1, 3, 3, 0, 3, 3, 3, 5, 5, 5, 7],
        active: [
            true, true, true, true, false, true, true, true, true, true, true, true,
        ],
        names: [
            "Gain",
            "Gate",
            "Env Follow",
            "Q",
            "",
            "Bands",
            "Min Frequency",
            "Max Frequency",
            "Input",
            "Range",
            "Center",
            "Mix",
        ],
    },
    SurgeFxParamLayout {
        fx_type: 11,
        display_name: "Reverb 2",
        posy_offset: [1, 3, 3, 3, 3, 3, 5, 5, 7, 7, 0, 0],
        active: [
            true, true, true, true, true, true, true, true, true, true, false, false,
        ],
        names: [
            "Pre-Delay",
            "Room Size",
            "Decay Time",
            "Diffusion",
            "Buildup",
            "Modulation",
            "LF Damping",
            "HF Damping",
            "Width",
            "Mix",
            "",
            "",
        ],
    },
    SurgeFxParamLayout {
        fx_type: 12,
        display_name: "Flanger",
        posy_offset: [23, -1, -1, -1, 1, 1, 1, 3, 3, 7, 7, 0],
        active: [
            true, true, true, true, true, true, true, true, true, true, true, false,
        ],
        names: [
            "Mode",
            "Waveform",
            "Rate",
            "Depth",
            "Count",
            "Base Pitch",
            "Spacing",
            "Feedback",
            "HF Damping",
            "Width",
            "Mix",
            "",
        ],
    },
    SurgeFxParamLayout {
        fx_type: 13,
        display_name: "Ring Modulator",
        posy_offset: [1, 1, 1, 1, 3, 3, 5, 5, 7, 0, 0, 0],
        active: [
            true, true, true, true, true, true, true, true, true, false, false, false,
        ],
        names: [
            "Shape",
            "Frequency",
            "Unison Detune",
            "Unison Voices",
            "Forward Bias",
            "Linear Region",
            "Low Cut",
            "High Cut",
            "Mix",
            "",
            "",
            "",
        ],
    },
    SurgeFxParamLayout {
        fx_type: 14,
        display_name: "Airwindows",
        posy_offset: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        active: [
            true, true, true, true, true, true, true, true, true, true, true, true,
        ],
        names: [
            "FX", "Param 0", "Param 1", "Param 2", "Param 3", "Param 4", "Param 5", "Param 6",
            "Param 7", "Param 8", "Param 9", "Param 10",
        ],
    },
    SurgeFxParamLayout {
        fx_type: 15,
        display_name: "Neuron",
        posy_offset: [1, 1, 1, 1, 1, 3, 3, 5, 5, 5, 7, 7],
        active: [
            true, true, true, true, true, true, true, true, true, true, true, true,
        ],
        names: [
            "Drive",
            "Squash",
            "Stab",
            "Asymmetry",
            "Bias",
            "Frequency",
            "Separation",
            "Waveform",
            "Rate",
            "Depth",
            "Width",
            "Gain",
        ],
    },
    SurgeFxParamLayout {
        fx_type: 16,
        display_name: "Graphic EQ",
        posy_offset: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3],
        active: [
            true, true, true, true, true, true, true, true, true, true, true, true,
        ],
        names: [
            "30 Hz", "60 Hz", "120 Hz", "250 Hz", "500 Hz", "1 kHz", "2 kHz", "4 kHz", "8 kHz",
            "12 kHz", "16 kHz", "Gain",
        ],
    },
    SurgeFxParamLayout {
        fx_type: 17,
        display_name: "Resonator",
        posy_offset: [1, 1, 1, 3, 3, 3, 5, 5, 5, 7, 7, 7],
        active: [
            true, true, true, true, true, true, true, true, true, true, true, true,
        ],
        names: [
            "Frequency 1",
            "Resonance 1",
            "Gain 1",
            "Frequency 2",
            "Resonance 2",
            "Gain 2",
            "Frequency 3",
            "Resonance 3",
            "Gain 3",
            "Mode",
            "Gain",
            "Mix",
        ],
    },
    SurgeFxParamLayout {
        fx_type: 18,
        display_name: "CHOW",
        posy_offset: [1, 1, 1, 3, 0, 0, 0, 0, 0, 0, 0, 0],
        active: [
            true, true, true, true, false, false, false, false, false, false, false, false,
        ],
        names: [
            "Threshold",
            "Ratio",
            "Flip",
            "Mix",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        ],
    },
    SurgeFxParamLayout {
        fx_type: 19,
        display_name: "Exciter",
        posy_offset: [1, 1, 3, 3, 5, 0, 0, 0, 0, 0, 0, 0],
        active: [
            true, true, true, true, true, false, false, false, false, false, false, false,
        ],
        names: [
            "Drive", "Tone", "Attack", "Release", "Mix", "", "", "", "", "", "", "",
        ],
    },
    SurgeFxParamLayout {
        fx_type: 20,
        display_name: "Ensemble",
        posy_offset: [1, 3, 3, 3, 3, 5, 5, 5, 5, 9, 9, 3],
        active: [
            true, true, true, true, true, true, true, true, true, true, true, true,
        ],
        names: [
            "Anti-Alias Filter",
            "Frequency 1",
            "Depth 1",
            "Frequency 2",
            "Depth 2",
            "Type",
            "Clock Rate",
            "Saturation",
            "Feedback",
            "Width",
            "Mix",
            "Reconstruction Filter",
        ],
    },
    SurgeFxParamLayout {
        fx_type: 21,
        display_name: "Combulator",
        posy_offset: [1, 3, 3, 3, 3, 3, 5, 5, 5, 7, 7, 7],
        active: [
            true, true, true, true, true, true, true, true, true, true, true, true,
        ],
        names: [
            "Extra Noise",
            "Center",
            "",
            "",
            "Feedback",
            "Tone",
            "Comb 1",
            "Comb 2",
            "Comb 3",
            "Pan 2",
            "Pan 3",
            "Mix",
        ],
    },
    SurgeFxParamLayout {
        fx_type: 22,
        display_name: "Nimbus",
        posy_offset: [1, 1, 3, 3, 3, 3, 3, 3, 5, 5, 7, 7],
        active: [
            true, true, true, true, true, true, true, true, true, true, true, true,
        ],
        names: [
            "Mode", "Quality", "Position", "Size", "Pitch", "Density", "Texture", "Spread",
            "Freeze", "Feedback", "Reverb", "Mix",
        ],
    },
    SurgeFxParamLayout {
        fx_type: 23,
        display_name: "Tape",
        posy_offset: [1, 1, 1, 1, 3, 3, 3, 3, 5, 5, 5, 7],
        active: [
            true, true, true, true, true, true, true, true, true, true, true, true,
        ],
        names: [
            "Drive",
            "Saturation",
            "Bias",
            "Tone",
            "Speed",
            "Gap",
            "Spacing",
            "Thickness",
            "Depth",
            "Amount",
            "Variance",
            "Mix",
        ],
    },
    SurgeFxParamLayout {
        fx_type: 24,
        display_name: "Treemonster",
        posy_offset: [1, 1, 1, 1, 3, 3, 5, 5, 0, 0, 0, 0],
        active: [
            true, true, true, true, true, true, true, true, false, false, false, false,
        ],
        names: [
            "Threshold",
            "Speed",
            "Low Cut",
            "High Cut",
            "Pitch",
            "Ring Modulation",
            "Width",
            "Mix",
            "",
            "",
            "",
            "",
        ],
    },
    SurgeFxParamLayout {
        fx_type: 25,
        display_name: "Waveshaper",
        posy_offset: [1, 1, 3, 3, 3, 5, 5, 7, 7, 0, 0, 0],
        active: [
            true, true, true, true, true, true, true, true, true, false, false, false,
        ],
        names: [
            "Low Cut", "High Cut", "Shape", "Bias", "Drive", "Low Cut", "High Cut", "Gain", "Mix",
            "", "", "",
        ],
    },
    SurgeFxParamLayout {
        fx_type: 26,
        display_name: "Mid-Side Tool",
        posy_offset: [1, 3, 3, 3, 3, 5, 5, 5, 5, 7, 7, 7],
        active: [
            true, true, true, true, true, true, true, true, true, true, true, true,
        ],
        names: [
            "Matrix",
            "Low Cut",
            "Gain",
            "Frequency",
            "High Cut",
            "Low Cut",
            "Gain",
            "Frequency",
            "High Cut",
            "Mid Gain",
            "Side Gain",
            "Balance",
        ],
    },
    SurgeFxParamLayout {
        fx_type: 27,
        display_name: "Spring Reverb",
        posy_offset: [1, 1, 1, 1, 3, 3, 3, 5, 0, 0, 0, 0],
        active: [
            true, true, true, true, true, true, true, true, false, false, false, false,
        ],
        names: [
            "Size",
            "Decay",
            "Reflections",
            "HF Damping",
            "Spin",
            "Chaos",
            "Knock",
            "Mix",
            "",
            "",
            "",
            "",
        ],
    },
    SurgeFxParamLayout {
        fx_type: 28,
        display_name: "Bonsai",
        posy_offset: [1, 3, 3, 5, 5, 5, 7, 7, 9, 9, 9, 0],
        active: [
            true, true, true, true, true, true, true, true, true, true, true, false,
        ],
        names: [
            "Gain",
            "Amount",
            "Distort",
            "Bias Filter",
            "Type",
            "Amount",
            "Sensitivity",
            "Gain",
            "Dull",
            "Gain",
            "Mix",
            "",
        ],
    },
];
