[package]
name = "clap-mml-render-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "clap-mml-render-server"
path = "src/main.rs"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
cmrt-core = { path = "../core-lib" }
cmrt-server-config = { path = "../server-config" }
ctrlc = "3"

[dev-dependencies]
toml = "1"
